FitocracyProyectoFinal/FitocracyProyectoFinal/Models/Tracks.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FitocracyProyectoFinal.Models
{
    [BsonIgnoreExtraElements(true)]
    public class Tracks
    {
        [BsonRepresentation(BsonType.ObjectId)]
        public string _id { get; set; }
        public string Nombre { get; set; }
        public string Link { get; set; }
        public int Series { get; set; }
        public int Repeticiones { get; set; }
    }
}

FitocracyProyectoFinal/FitocracyProyectoFinal/Controllers/FotosController.cs
using FitocracyProyectoFinal.Models;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitocracyProyectoFinal.Controllers
{
    public class FotosController : Controller
    {
        #region Variables
        private MongoDBcontext _dbContext;
        public FotosController()
        {
            _dbContext = new MongoDBcontext();
        }
        #endregion

        #region Métodos 
        public ActionResult downloadPhoto(string id)
        {
            var usu = _dbContext.Usuarios.Find<Usuario>(x => x._id == id).SingleOrDefault();
            return File(usu.Foto, "image/jpg");
        }

        public ActionResult showFotoEntrenamiento(string id)
        {           
            var entrenamiento = _dbContext.Entrenamientos.Find<Entrenamientos>(x => x._id == id).SingleOrDefault();
            return File(entrenamiento.Foto, "image/jpg");
        }

        public ActionResult showEntrenador(string id)
        {          
            var usu = _dbContext.Entrenadores.Find<Entrenadores>(x => x._id == id).SingleOrDefault();
            return File(usu.Foto, "image/jpg");
        }
        #endregion
    }
}

FitocracyProyectoFinal/FitocracyProyectoFinal/Controllers/ZonaUsuariosController.cs
using FitocracyProyectoFinal.Models;
using MongoDB.Bson;
using MongoDB.Driver;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitocracyProyectoFinal.Controllers
{
    public class ZonaUsuariosController : Controller
    {
        #region Variables
        private MongoDBcontext _dbContext;
        private Usuario _usuario;
        public ZonaUsuariosController()
        {
            _dbContext = new MongoDBcontext();
        }

        public Usuario usuario
        {
            get
            {
                return _usuario = (Usuario)Session["infoUsuario"];
            }
            set
            {
                this._usuario = value;
            }
        }
        #endregion

        #region Vistas
        public ActionResult Home()
        {
            return PartialView(usuario);
        }
        public ActionResult You()
        {
            var usu = _dbContext.Usuarios.Find<Usuario>(x => x._id == usuario._id).SingleOrDefault();
            int puntos = pointsToNextLevel(usu);
            ViewData["pointsToNextLevel"] = puntos;
            ViewData["nextLevel"] = usu.Level + 1;
            return View(usu);
        }
       
        public ActionResult Track()
        {
            return View(usuario);
        }
        public ActionResult Connect()
        {
            return View(usuario);
        }
        public ActionResult Leaders()
        {
           var listLeaders = _dbContext.Usuarios.Find<Usuario>(new BsonDocument()).Sort(Builders<Usuario>.Sort.Descending(x=>x.Points)).ToList();
            return View(listLeaders);
        }

        public ActionResult WorkoutDoneAlert()
        {
            var usu = _dbContext.Usuarios.Find<Usuario>(x => x._id == usuario._id).SingleOrDefault();
            return View(usu);
        }
        #endregion

        #region Métodos de trasiego de datos

        /// <summary>
        /// Método invocado desde userCtrl.js
        /// Borra de la sesión al ususario
        /// </summary>
        /// <param name="idUsuario"></param>
        public void SignOut(string idUsuario)
        {
            Session["infoUsuario"] = null;
        }


        /// <summary>
        /// Método invocado desde WorkoutCarruselPV.cshtml
        /// Guarda en la Base de datos el entrenamiento que el usuario acaba de realizar
        /// Suma los puntos obtenidos y comprueba que el nivel es el correcto
        /// </summary>
        /// <param name="_idWorkout"></param>
        /// <returns>Redirige a WorkoutAlert.cshtml</returns>
        [HttpPost]
        public ActionResult workoutDone(string _idWorkout)
        {
            var host = Request.Url.Host;
            var port = Request.Url.Port;

            try
            {
                var workCollection = _dbContext.Workouts.Find<Workouts>(x => x._id == _idWorkout).FirstOrDefault();
                var usuCollection = _dbContext.Usuarios.Find<Usuario>(x => x._id == usuario._id).SingleOrDefault();
                usuCollection.WorkoutsUser.Add(DateTime.Now.ToString(), workCollection);
                _dbContext.Usuarios.UpdateOne<Usuario>(x => x._id == usuario._id, Builders<Usuario>.Update.Set(x => x.WorkoutsUser, usuCollection.WorkoutsUser));


                usuCollection.Points += workCollection.Puntos;
                _dbContext.Usuarios.UpdateOne<Usuario>(x => x._id == usuario._id, Builders<Usuario>.Update.Set(x => x.Points, usuCollection.Points));

                int levelActual = compruebaNivelActual(usuCollection.Points);
                if (levelActual != usuCollection.Level)
                {
                    usuCollection.Level = levelActual;
                    _dbContext.Usuarios.UpdateOne<Usuario>(x => x._id == usuario._id, Builders<Usuario>.Update.Set(x => x.Level, usuCollection.Level));
                }


                string yearActual = DateTime.Today.Year.ToString();
                string mesActual = DateTime.Today.Month.ToString();

                //Si no existe el año dentro del dictionary es porque es AÑO NUEVO
                if (!usuCollection.EvolutionUser.ContainsKey(yearActual))
                {
                    Dictionary<string, Dictionary<string, int>> nuevoDicAnyo = new Dictionary<string, Dictionary<string, int>>();
                    Dictionary<string, int> nuevoDicMeses = new Dictionary<string, int>();

                    for (int i = 0; i < 12; i++)
                    {
                        nuevoDicMeses.Add((i + 1).ToString(), 0);
                    }

                    nuevoDicAnyo.Add(yearActual, nuevoDicMeses);
                }

                var dicMeses = usuCollection.EvolutionUser.Where(x => x.Key == yearActual).SingleOrDefault().Value;

                int puntosMes = 0;

                foreach (var mes in dicMeses)
                {
                    if (mes.Key.Equals(mesActual))
                    {
                        puntosMes = mes.Value;
                        puntosMes += workCollection.Puntos;
                    }
                }

                dicMeses[mesActual] = puntosMes;

                _dbContext.Usuarios.UpdateOne<Usuario>(x => x._id == usuario._id, Builders<Usuario>.Update.Set(x => x.EvolutionUser[yearActual], dicMeses));
               
            }
            catch (Exception e)
            {
                string ex = e.ToString();
            }

            return Redirect("http://" + host + ":" + port + "/#/WorkoutDoneAlert");
        }

        
        /// <summary>
        /// Método invocado desde trackService.js
        /// Recupera todos los Workouts
        /// </summary>
        /// <returns>Lista de Workouts</returns>
        [HttpPost]
        public string recuperaWorkouts()
        {
            try
            {
                var workouts = _dbContext.Workouts.Find<Workouts>(new BsonDocument()).ToList();
                return JsonConvert.SerializeObject(workouts);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Método invocado desde trackService.js
        /// Recupera todos los Workouts del usuario
        /// </summary>
        /// <returns>Lista de Workouts</returns>
        [HttpPost]
        public string recuperaWorkoutsUsu()
        {
            try
            {
                var usuCollection = _dbContext.Usuarios.Find<Usuario>(x => x._id == usuario._id).FirstOrDefault();
                return JsonConvert.SerializeObject(usuCollection.WorkoutsUser);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Método invocado desde trackService.js
        /// Recupera todos los tracks 
        /// </summary>
        /// <returns>Lista de Tracks</returns>
        [HttpPost]
        public string recuperaAllTracks()
        {
            try
            {
                var tracks = _dbContext.Tracks.Find<Tracks>(new BsonDocument()).ToList();
                return JsonConvert.SerializeObject(tracks);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Método invocado desde trackService.js
        /// Recupera todos los Workouts diseñados por el usuario
        /// </summary>
        /// <returns>Lista de Workouts</returns>
        [HttpPost]
        public string recuperaCustomWorkouts()
        {
            try
            {
                var usuCollection = _dbContext.Usuarios.Find<Usuario>(x => x._id == usuario._id).FirstOrDefault();
                return JsonConvert.SerializeObject(usuCollection.CustomWorkouts);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Método invocado desde trackService.js
        /// Busca el track 
        /// </summary>
        /// <param name="textoBusqueda"></param>
        /// <returns>Listado de tracks coincidentes con la búsqueda</returns>
        [HttpPost]
        public string buscadorTracks(string textoBusqueda)
        {
            try
            {
                var tracksEncontrados = _dbContext.Tracks.Find<Tracks>(x => x.Nombre.Contains(textoBusqueda)).ToList();
                return JsonConvert.SerializeObject(tracksEncontrados);
            }
            catch (Exception e)
            {
                string ex = e.ToString();
                return null;
            }
        }

        /// <summary>
        /// Transforma la foto del usuario en un array de bytes y la guarda en la base de datos
        /// </summary>
        /// <param name="file"></param>
        /// <param name="idUsu"></param>
        /// <returns>Redirige a You.cshtml</returns>
        [HttpPost]
        public ActionResult uploadPhoto(HttpPostedFileBase file, string idUsu)
        {
            var host = Request.Url.Host;
            var port = Request.Url.Port;

            var url = Url.RequestContext.RouteData.Values["id"];
            if (file != null)
            {
                string pic = Path.GetFileName(file.FileName);
                string path = Path.Combine(Server.MapPath("~/Content/Imagenes/Profiles"), pic);
                file.SaveAs(path);

                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();

                    try
                    {

FitocracyProyectoFinal/FitocracyProyectoFinal/Views/ZonaUsuarios/Connect.cshtml
@model FitocracyProyectoFinal.Models.Usuario

<h3>Hey @Model.Username</h3>
<p>Please tell us the following: your age, gender, fitness history, fitness goals, and what kind of equipment/gym access you have. We'll get back to you with our recommendation as quickly as we can.</p>
<div class="row" ng-controller="youCtrl">
        <div class="container input-group text-center">
            <textarea id="areaMessage" name="areaMessage" rows="10" cols="150" placeholder="We're not around but we still want to hear from you!  Leave us a note:"></textarea>
        </div>
        <br />
        <div class="container text-center">
            <input type="submit" class="btn btn-primary btn-lg" ng-click="Connect()" value="Send" />
            @*<button type="submit" class="btn btn-primary btn-lg" style="width:300px;">Send</button>*@
        </div>   
</div>

<div id="modalMessageSend" class="modal fade" tabindex="-1" role="dialog" ng-controller="youCtrl">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>CONNECT OK!!</h2>
            </div>

            <div class="modal-body">
                <p>Your email has sent correctly!! We're working to answer as soon as possible!!</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" ng-click="cerrarConnect()">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


FitocracyProyectoFinal/FitocracyProyectoFinal/Views/ZonaUsuarios/Home.cshtml
@model FitocracyProyectoFinal.Models.Usuario

<div class="text-center">
    <div class="row">
        <div class="col-lg-4 col-md-4 pull-left">
            <img src="~/Content/Imagenes/logo.png" />
        </div>
        <div class="col-lg-2 col-md-2"></div>
        <div class="col-lg-4 col-md-4 pull-right">
            <p style="font-size:15px;">WELCOME!! @Model.Username</p>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-12 col-md-12 center">
            <img src="~/Content/Imagenes/Portadas/portadaZonaUsu.jpg" sstyle="width:90%; height:480px" />
        </div>
    </div>
    <hr />
    @Html.Partial("~/Views/PartialsViews/ServicesPV.cshtml", "usu")
</div>

FitocracyProyectoFinal/FitocracyProyectoFinal/Views/ZonaUsuarios/Leaders.cshtml
@using FitocracyProyectoFinal.Models
@model List<Usuario>

<style>
    .redondo img {
        border: 2px solid #fff;
        margin: 0;
        padding: 0;
        border-radius: 800px;
        overflow: hidden;
    }
</style>

<div class="table-responsive">
    <table id="tablaWorkout" class="table table-striped center" style="text-align:center; width:100%; height:100%">
        <tr>
            <td rowspan="2" style="width:30%; border-right:1px solid grey; border-left:1px solid grey">
                <img src="~/Content/Imagenes/leader.PNG" class="center" style="width:320px; height:320px" />
                <h3 style="text-align:center">Community Spotlight</h3>
                <p style="text-align:center">Take some yoga, throw in a little cardio and mix with weight training and you've got Omyeah, Fitocracy's self professed spiritual gansta. A leader in our Yogis and Yoginis group, Omyeah is one strong, zen lovin', awesome cat momma. Connect with her and other Fito Yoginis in our Lady Lifters group.</p>
            </td>
            <td style="width:70%; border-right:1px solid grey; vertical-align:top">
                <table id="tablaLeaders" class="table center" style="text-align:center; width:100%; height:100%; vertical-align:top">
                    
                    <tr style="background-color:#f4f5f5">
                        <th style="text-align:center">Standing</th>
                        <th style="text-align:center">Name</th>
                        <th style="text-align:center">Level</th>
                        <th style="text-align:center">Points</th>
                    </tr>

                    @{
                        for (int i = 0; i < Model.Count(); i++)
                        {
                            <tr>
                                <td>
                                    @{
                                        int pos = i + 1;
                                    }
                                    <p style="color:#1F2B32; font-size:medium; float:left; font-size:30px; vertical-align:central">@pos</p>
                                </td>
                                <td>
                                    <img src='@Url.Action("downloadPhoto", "Fotos", new { id = Model[i]._id})' class="pull-left" style="margin:0; padding:0; border:0; outline:0; height:100px; width:100px" />
                                    <p style="font-size:medium; display:inline-block">@Model[i].Username</p>
                                </td>
                                <td>
                                    <p style="font-size:medium;">@Model[i].Level</p>
                                </td>
                                <td>
                                    <p style="font-size:medium;">@Model[i].Points</p>
                                </td>
                            </tr>
                                        }

                    }
                </table>
            </td>
        </tr>
    </table>
</div>

FitocracyProyectoFinal/FitocracyProyectoFinal/Views/ZonaUsuarios/Track.cshtml
<div class="row" ng-controller="trackCtrl">
    <!--COLUMNA IZQUIERDA-->
    <div class="col-lg-4 col-md-4">

        <div id="busqueda">
            <form class="form-inline">
                <div class="form-group">
                    <div class="input-group">
                        <input id="textBusqueda" name="textBusqueda" type="text" class="form-control" placeholder="Search" ng-model="textBusqueda" />
                    </div>
                </div>
                <button type="button" class="btn btn-default" ng-click="buscar()">Search</button>
            </form>
        </div>
        <br />
        <hr />

        <div id="subMenu">
            <div id="preMade">
                <a class="pointer" id="link_preMadeWorkouts" ng-click="showDiv('preMadeWorkouts', $event)" show="false" style="font-size:medium; font-weight:bold">Pre-Made workouts  <i class="fa fa-chevron-up" aria-hidden="true"></i></a>
                <br />

                <div id="preMadeWorkouts" style="display:none">
                    <div ng-repeat="preW in preMadeWorkouts track by preW._id">
                        <a class="pointer" style="font-size:medium" ng-click="descripcionEnPartial('preMadeWorkouts', $event)" data="{{preW._id}}">{{preW.Nombre}}</a>
                        <span>{{preW.Puntos}}</span>
                    </div>
                </div>
            </div>
            <hr />
            <br />
            <div id="recent">
                <a class="pointer" id="link_recentWorkouts" ref="showDiv" ng-click="showDiv('recentWorkouts', $event)" show="false" style="font-size:medium; font-weight:bold">Recent workouts  <i class="fa fa-chevron-up" aria-hidden="true"></i></a>
                <br />
                <div id="recentWorkouts" style="display:none">
                    <div ng-repeat="(key, value) in recentWorkouts track by key">
                        <a class="pointer" style="font-size:medium" ng-click="descripcionEnPartial('recentWorkouts', $event)" data="{{value._id}}">{{value.Nombre}}</a>
                        <span><small>{{key}}</small> {{value.Puntos}}</span>
                    </div>
                </div>
            </div>

            <hr />
            <br />
            <div id="custom">
                <a class="pointer" id="link_customWorkouts" ref="showDiv" ng-click="showDiv('customWorkouts', $event)" show="false" style="font-size:medium; font-weight:bold">My custom Workouts!!  <i class="fa fa-chevron-up" aria-hidden="true"></i></a>
                <br />
                <div id="customWorkouts" style="display:none">
                    <div ng-repeat="(key, value) in customWorkouts track by key">
                        <a class="pointer" style="font-size:medium" ng-click="descripcionEnPartial('customWorkouts', $event)" data="{{value._id}}">{{value.Nombre}}</a>
                        <span><small>{{key}}</small></span> 
                        <a ng-click="borrarMyWork(key)" class="pointer"><span style="color:red"><i class="fa fa-trash-o" aria-hidden="true"></i></span></a>
                    </div>
                </div>
            </div>
            <hr />
            <br />
            <div id="factory">
                <a class="pointer" style="font-size:medium; font-weight:bold" ng-click="workoutsFactory()">Make your own Workout!!</a>
            </div>
        </div>
        <hr />
        <br />
        <div id="all">
            <a class="pointer" id="link_allTracks" ref="showDiv" ng-click="showDiv('allTracks', $event)" show="false" style="font-size:medium; font-weight:bold">All Tracks  <i class="fa fa-chevron-up" aria-hidden="true"></i></a>
            <br />
            <div id="allTracks" style="display:none">
                <div ng-repeat="track in allTracks | orderBy: 'Nombre' track by track._id">
                    <a class="pointer" style="font-size:medium" ng-click="trackEnPartial($event)" data="{{track._id}}">{{track.Nombre}}</a>
                </div>
            </div>
        </div>
    </div>

    <!--COLUMNA DERECHA-->
    <div class="col-lg-8 col-md-8" id="vistaParcial">
        <div id="divBusqueda" style="display:none">
            <h2 style="text-align:center; color:#1f2b32">Search Results</h2>
            <hr />
            <div ng-repeat="encontrado in tracksEncontrados | orderBy: 'Nombre' track by encontrado._id">
                <ul>
                    <li>
                        <a class="pointer" style="font-size:medium" ng-click="trackEnPartial($event)" data="{{encontrado._id}}">{{encontrado.Nombre}}</a>
                    </li>
                </ul>
            </div>
        </div>

    </div>

</div>



FitocracyProyectoFinal/FitocracyProyectoFinal/Views/ZonaUsuarios/You.cshtml
@model FitocracyProyectoFinal.Models.Usuario

<div class="row">
    <!--COLUMNA IZQUIERDA-->
    <div class="col-lg-4 col-md-4">
        <img src='@Url.Action("downloadPhoto", "Fotos", new { id= Model._id })' height="300" width="300" />
        @using (Html.BeginForm("uploadPhoto", "ZonaUsuarios", new { id = Model._id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <input type="file" name="file" id="file" style="width: 100%;" class="center" />
            <input type="hidden" name="idUsu" value="@Model._id" />
            <input type="submit" value="Upload Image:" class="btn btn-upload btn-block center" />
        }
    </div>
    <!--COLUMNA DERECHA-->
    <div class="col-lg-8 col-md-8 pull-left" style="text-align:left; background-color:#f8f8f8; height:300px; border:1px solid #e7e7e7">
        <h2>USER INFO</h2>
        <p><strong>User Name:</strong> @Model.Username</p>
        <p><strong>Email:</strong> @Model.Email</p>
        <p><strong>Description:</strong> @Model.Description</p>
        <p style="color:#8F9A9E;">@ViewData["pointsToNextLevel"]  pts to Level @ViewData["nextLevel"]</p>
    </div>
</div>
<br />
<br />

<div class="row" style="background-color:#1F2B32; color:#FFF; text-align:center" height="80px">
    <div class="col-lg-4 col-md-4"><h2>@Model.Level</h2><small>Level</small></div>
    <div class="col-lg-4 col-md-4"><h2>@Model.Points</h2><small>Points</small></div>
    <div class="col-lg-4 col-md-4">
        @{
            if (Model.Age == 0)
            {
                <h2>?</h2><small>Age</small>
            }
            else
            {
                <h2>@Model.Age</h2><small>Age</small>
            }
        }
    </div>
</div>
<br />
<hr />
<div class="row" ng-controller="youCtrl">
    <!--COLUMNA IZQUIERDA-->
    <div class="col-lg-4 col-md-4">
        <h4><a class="pointer" id="link_divYou" ng-click="showDiv('divYou', $event)" show="false">User Info<i class="fa fa-chevron-up" aria-hidden="true"></i></a></h4>
        <div id="divYou" style="display:none">
            <ul>
                <li><h4><a class="pointer" id="userInfo" ng-click="cargaPartial($event)">About you</a><br /></h4></li>
                <li><h4><a class="pointer" id="userChangePass" ng-click="cargaPartial($event)">Change Password</a><br /></h4></li>
            </ul>
        </div>
        <h4><a class="pointer" id="userWorkouts" ng-click="cargaPartial($event)">My Workouts Done</a><br /></h4>
        <h4><a class="pointer" id="userEvolution" ng-click="cargaPartial($event)">My Evolution</a><br /></h4>
        <h4><a class="pointer" id="summaryLevels" ng-click="cargaPartial($event)">Summary Levels</a><br /></h4>
    </div>
    <!--COLUMNA DERECHA-->
    <div class="col-lg-8 col-md-8 pull-left" style="text-align:left;" id="vistaParcial">

    </div>
</div>

<!--MODAL-->
<div id="modalChangesOK" class="modal fade" tabindex="-1" role="dialog" ng-controller="youCtrl">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>CHANGES OK!!</h2>
            </div>

            <div class="modal-body">
                <p>Your changes has been modified correctly!!</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" ng-click="cerrarChangesOK()">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
